### ISSUE TITLE
Exception in thread "main" java.lang.reflect.InvocationTargetException when building CallGraph

### ISSUE THREAD

**Issue by louison** [USC-SQL/Violist#2]
Hi,
I'm still trying to use Violist. :-)

```
For every APK I tried, I always get this error : 
[Call Graph] For information on where the call graph may be incomplete, use the verbose option to the cg phase.
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.RuntimeException: no superclass for javax.management.openmbean.OpenType
	at soot.SootClass.getSuperclass(SootClass.java:784)
	at soot.jimple.toolkits.typing.fast.BytecodeHierarchy.buildAncestryTree(BytecodeHierarchy.java:84)
	at soot.jimple.toolkits.typing.fast.BytecodeHierarchy.lcas_(BytecodeHierarchy.java:193)
	at soot.jimple.toolkits.typing.fast.BytecodeHierarchy.lcas_(BytecodeHierarchy.java:148)
	at soot.jimple.toolkits.typing.fast.BytecodeHierarchy.lcas(BytecodeHierarchy.java:107)
	at soot.jimple.toolkits.typing.fast.TypeResolver.applyAssignmentConstraints(TypeResolver.java:510)
	at soot.jimple.toolkits.typing.fast.TypeResolver.inferTypes(TypeResolver.java:150)
	at soot.jimple.toolkits.typing.TypeAssigner.internalTransform(TypeAssigner.java:125)
	at soot.BodyTransformer.transform(BodyTransformer.java:59)
	at soot.BodyTransformer.transform(BodyTransformer.java:64)
	at soot.dexpler.DexBody.jimplify(DexBody.java:593)
	at soot.dexpler.DexMethod$1.getBody(DexMethod.java:142)
	at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:111)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:349)
	at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.processNewMethod(OnFlyCallGraphBuilder.java:1058)
	at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.processReachables(OnFlyCallGraphBuilder.java:533)
	at soot.jimple.toolkits.callgraph.CallGraphBuilder.build(CallGraphBuilder.java:104)
	at soot.jimple.toolkits.callgraph.CHATransformer.internalTransform(CHATransformer.java:46)
	at soot.SceneTransformer.transform(SceneTransformer.java:39)
	at soot.SceneTransformer.transform(SceneTransformer.java:45)
	at soot.SceneTransformer.transform(SceneTransformer.java:50)
	at SootEvironment.AndroidApp.<init>(AndroidApp.java:157)
	at usc.sql.string.JavaAndroid.<init>(JavaAndroid.java:58)
	at usc.sql.string.AndroidMain.main(AndroidMain.java:41)
```

I'm thinking about a wrong android.jar (I used the one which is in example/android--1).

What do you think ?
I took a look on the source code and Violist seems to fit perfectly for my needs.
Thank you in advance for yout answer

**Comment by winsonlyu** [comment]
It seems to be soot's limitation in loading the super class of javax.management.openmbean.OpenType. I think you may need to configure soot to load not only android.jar but also rt.jar.

**Comment by louison** [comment]
Do you mean that I have to modify soot configuration in your source code in order to take rt.jar and android.jar into account and then re-build Violist ?
Because your soot configuration seems to be bundled into the graphs.jar, so I can't access it

**Comment by winsonlyu** [comment]
The source code is available here: https://github.com/USC-SQL/graphs
