### ISSUE TITLE
Testcases not working

### ISSUE THREAD

**Issue by MarcMil** [USC-SQL/Violist#6]
The test cases seem to contain several hardcoded paths:
```
	String rtjar = "/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/rt.jar";
	String appfolder = "/home/yingjun/Documents/StringAnalysis/Testing/";	
	String gt = "/home/yingjun/Documents/eclipse/workspace/StringTestCases/groundtruth/";
```

Also, it is not clear how to run the test cases. I've imported the project into eclipse using the m2e connector and added the test cases to the build path.
It would be better if tests were run via maven.

LoopNodeTest1 and 2 fail due to a null pointer:
```
java.lang.NullPointerException
	at usc.sql.string.LayerRegion.dfsReverse(LayerRegion.java:160)
	at usc.sql.string.LayerRegion.identifyLoopSet(LayerRegion.java:122)
	at usc.sql.string.test.LoopNodeTest2.test(LoopNodeTest2.java:135)
```

**Comment by winsonlyu** [comment]
The test case  are outdated. We will update them as soon as possible. Our replication package and the complete test cases are hosted here (https://github.com/marapapman/Violist). If you want to try your own examples, the current way you are using is good, i.e., creating your own toy app and running Violist on it.
